[package]
name = "vros-steamvr-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = "5.1.1"
serde = { version = "1.0.139", features = ["derive"] }
thiserror = "1.0.31"
